import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const handleLogin = async () => {
    const response = await login();
    localStorage.setItem("ACCESS_TOKEN", response.data.accessToken);
  };

  const login = (): any => {
    return axios.post(
      "http://localhost:8081/api/auth/signin",
      {
        usernameOrEmail: "yumi3119@dti.ad.jp",
        password: "password",
      },
      {
        headers: {
          "Content-Type": "application/json",
        },
      }
    );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <a href="http://localhost:8081/oauth2/authorization/google?redirect_uri=http://localhost:3000">
            google
          </a>
          <button onClick={handleLogin}>ログイン</button>
          <button
            onClick={async () => {
              await axios.get("http://localhost:8081/api/users");
            }}
          >
            ユーザー表示
          </button>
          <button
            onClick={async () => {
              await axios.get("http://localhost:8081/api/logout", {
                headers: {
                  Authorization: `Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0IiwiaWF0IjoxNjcyODk5MzE3LCJleHAiOjE2NzI5MDI5MTd9.alG3n-FxpDJCzG5JVhgg8cbhYO2ap_ewDQQzKIyFLZRNVzUUODijhy8m_FDtQoExopVeGlMhQHEjr8D-DnRQag`,
                },
              });
            }}
          >
            ログアウト
          </button>
        </div>
      </main>
    </>
  );
}
